### PR TITLE
[WIP] Ui design

### PR DESCRIPTION
**Pull request by nitro8708**
- add comments for previous code
- add fb/twitter sharing links.
- add BGM for the homepage (in the comment part, not good performance )

### CODE REVIEW

**Comment by yuyafukuchi** [comment]
おお

**Comment by yuyafukuchi** [comment]
Can you build this? I cannot build via command 'yarn watch'

**Comment by nitro8708** [comment]
Sorry now I have just done this part separately with other parts, how to aggregate them with the game function?  Do you need all the pages that I have created?

**Comment by yuyafukuchi** [comment]
ok!!If you have not done your work, you had better name pull requests [WIP]xxxxxx!☺️

**Comment by nitro8708** [comment]
ok i see!

**Pull request closed without merging**
